// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb-WvW8UuIQtlT3wbWf5R7xokSkMMHL20',
    appId: '1:958795741898:web:932a286088726c3aae9233',
    messagingSenderId: '958795741898',
    projectId: 'taxilamart-5b262',
    authDomain: 'taxilamart-5b262.firebaseapp.com',
    storageBucket: 'taxilamart-5b262.firebasestorage.app',
    measurementId: 'G-R4HQJLZ254',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhh4c-fmoGZyR5rCUR9mmCc33PZQRxbrk',
    appId: '1:958795741898:android:b4d4ab0ac5eb9801ae9233',
    messagingSenderId: '958795741898',
    projectId: 'taxilamart-5b262',
    storageBucket: 'taxilamart-5b262.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT-qfqhOxgiic3o98Xoangrp6UkZROTkA',
    appId: '1:958795741898:ios:94407f442185a52cae9233',
    messagingSenderId: '958795741898',
    projectId: 'taxilamart-5b262',
    storageBucket: 'taxilamart-5b262.firebasestorage.app',
    iosBundleId: 'com.app.taxilamartuser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7ZutxPQPMZ-QLC1L_rIO1eDOGmEMoI20',
    appId: '1:746182761504:ios:d9b4dcd524a8b4a69cf045',
    messagingSenderId: '746182761504',
    projectId: 'uttammart-b46eb',
    storageBucket: 'uttammart-b46eb.firebasestorage.app',
    iosBundleId: 'com.app.taxilamartuser',
  );
}