// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyLeG3JvoAt9KNWcwZ0XHvEHaTpzyKsvM',
    appId: '1:746182761504:web:254b97468b07d75c9cf045',
    messagingSenderId: '746182761504',
    projectId: 'uttammart-b46eb',
    authDomain: 'uttammart-b46eb.firebaseapp.com',
    storageBucket: 'uttammart-b46eb.firebasestorage.app',
    measurementId: 'G-35HVPCYYT8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1mZ1F0ZYIs0mDkjTDFlDpkEsS9hvCmQI',
    appId: '1:746182761504:android:9e7c80400f01496e9cf045',
    messagingSenderId: '746182761504',
    projectId: 'uttammart-b46eb',
    storageBucket: 'uttammart-b46eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7ZutxPQPMZ-QLC1L_rIO1eDOGmEMoI20',
    appId: '1:746182761504:ios:d9b4dcd524a8b4a69cf045',
    messagingSenderId: '746182761504',
    projectId: 'uttammart-b46eb',
    storageBucket: 'uttammart-b46eb.firebasestorage.app',
    iosBundleId: 'com.app.uttammartuser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7ZutxPQPMZ-QLC1L_rIO1eDOGmEMoI20',
    appId: '1:746182761504:ios:d9b4dcd524a8b4a69cf045',
    messagingSenderId: '746182761504',
    projectId: 'uttammart-b46eb',
    storageBucket: 'uttammart-b46eb.firebasestorage.app',
    iosBundleId: 'com.app.uttammartuser',
  );
}
